### ISSUE TITLE
Docker toolbox: Can’t get class Ctrm

### ISSUE THREAD

**Issue by pyotr777** [docker/toolbox#178]
Just installed toolbox on OSX from here: https://www.docker.com/toolbox.
When I start it get error
```
iTerm got an error: Can’t get «class Ctrm». (-1728)
```
OSX version 10.10.5.

**Comment by jeffdm** [comment]
Which version of iTerm are you running?

**Comment by pyotr777** [comment]
I have iterm2 Build 2.9.20150908-nightly.

**Comment by ggrell** [comment]
<img width="416" alt="screen shot 2015-09-14 at 9 33 09 am" src="https://cloud.githubusercontent.com/assets/107712/9850881/a08467f0-5ac3-11e5-8f2e-05f602a27955.png">
iTerm2 Build 2.9.20150830

**Comment by jjmiv** [comment]
getting same error.  have tried to reinstall both iTerm2 and Docker Toolbox but get same error.

**Comment by digitalfiz** [comment]
I'm getting it too... Any way to reset the default so I can chose Terminal until its fixed?

**Comment by jeffdm** [comment]
This should be fixed in the latest version - can you verify?

**Comment by jjmiv** [comment]
just installed 1.8.2c and there are no errors when I open up Docker Quickstart Terminal into iTerm 2.  Thanks!

**Comment by jeffdm** [comment]
Great to know! I'm going to close this for now, but feel free to re-open if the error still occurs.

**Comment by spindelmanne** [comment]
I'm getting this problem with 1.10.3. 

Reinstall didn't help, and the file /Library/Application\ Support/DockerToolbox/default_terminal isn't there, so I can't remove it.

**Comment by spindelmanne** [comment]
OK, I missed the fact that it was under my home directory (silly me!) so now I've been able to set it back to Terminal, but I still can't use DQT with iTerm.

My iTerm version is 3.0.2.
